### ISSUE TITLE
qgis-214 failed to build on 10.10.5

### ISSUE THREAD

**Issue by ivanmobigis** [OSGeo/homebrew-osgeo4mac#128]
Hello,

qgis-214 does not compile on my 10.10.5 machine. i previously had qgis-28 working fine. now even it is broken so i am without qgis :(

It gets to 88% and then dies with:
[ 88%] Built target qgis_app
make: *** [all] Error 2

i can't find any useful statements in the log about which library / where the problem could be.

i ran brew update for the install, brew doctor reports nothing.

I have tried the install / uninstall / reinstall trick.

here is the gist-logs:

https://gist.github.com/968fa6ac3b7582e5c9cf98cd78c23866

what other info should i supply to help debug this ?

cheers and thanks

-i

**Comment by ivanmobigis** [comment]
to complete my above message, i managed to get qgis-28 working again by:

- uninstalling qgis-214 and qgis-28
- uninstalling qscintilla2 (qgis-28 had been complaining about it after the qgis-214 install)
- brew tap homebrew/science (because brew asked for this when i ran "brew deps qgis-28")
- installing qgis-28

i can retry qgis-214 if anyone has any ideas from the gist posted above.

cheers

**Comment by pjduplooy** [comment]
Hi ivanmobigis.

Have you had any of the --with flags on?

Tried to compile with gdal 1 or 2?

I built mine over the weekend with r, grass7, orfeo and saga enabled but not server.

My built worked.

**Comment by ivanmobigis** [comment]
hey pjduplooy,

i didn't use any flags for the qgis-214 build.. so the qgis-server would have been included.

osgeo/osgeo4mac/gdal-20 was installed with qgis-28 and works fine..so it is / was present for the qgis-214 install.  it is referenced throughout the gist log.

are you on max os 10.10.5 also ?

**Comment by pjduplooy** [comment]
ivanmobigis

Using El Capitan, so 10.11.something.

I am perusing your make output to see if I can see anything.  I have used gdal 1 for the sake of other installs like postgis etc

**Comment by pjduplooy** [comment]
By the way, have for the first time in ages built postgis with extensions, grass, qgis, orfeo-42 (for that I changed cmake to 2.8), pdal, pcl, saga and others

**Comment by pjduplooy** [comment]
Something strange in your build log....MacOSX 10.11 sdk.. Dont know enough about homebrew to say if thats right.

**Comment by ivanmobigis** [comment]
thanks for the feedback, 

MacOSX 10.11 sdk is xcode, the latest one.

my cmake is  cmake: stable 3.5.1

i have postgis installed, it is working fine also.

darwin ivan ~ $ brew info postgis
postgis: stable 2.2.1 (bottled), HEAD

-i

**Comment by pjduplooy** [comment]
Would you mind building again and disabling fcgi?

**Comment by ivanmobigis** [comment]
hey, ok i'll try that now. i'll let you know how it goes tomorrow coz i'm out the door right now.

thanks for the help !

**Comment by pjduplooy** [comment]
No prob

**Comment by ivanmobigis** [comment]
hello again,

this time i ran the install like this:

brew install qgis-214 --without-server

(iis that what you meant by 'disabling fcgi' ?) i also uninstalled brew's fcgi module before the install, which had been installed before. It was not replaced when this install ran.

the install died at the same place i believe:
[ 90%] Linking CXX shared library ../../output/lib/libqgis_app.dylib

but there's no explanation why.


the gist for this run is here:
https://gist.github.com/697a053120869b57cfb2d0d687ed79ff


cheers

-i

**Comment by ivanmobigis** [comment]
i'll just add a note here in case it's useful for anyone else. after installing (trying to install) qgis-214 you can't just uninstall qgis-214 and install qgis-28 directly, coz qgis-28 expects different versions of all the dependencies which have now been upgraded. i was obliged to install qgis using a --with or --without flag to fore its recompilation to make it play nicely with the dependancies present on the system.

so in my case:
brew install qgis-28  installed qgis (from the bottle) correctly but gave dylib errors on running.
brew install qgis-28 --without-server  forced the recompile and runs fine.

-i

**Comment by pjduplooy** [comment]
Hi

Can you give indication to what deps have been upgraded?

The only difference I can see between your build and mine, is that with mine, system Python was used. But that would not make mine work, and yours fail, or could it?

**Comment by pjduplooy** [comment]
Ok, I see something interesting in your make log:

[ 77%] Generating ui/moc_qgsgeometrycheckerdialog.cxx
cd /tmp/qgis-21420160412-74199-l8k42e/QGIS-final-2_14_1/build/src/plugins/geometry_checker/ui && /usr/local/Cellar/qt/4.8.7_2/bin/moc @/tmp/qgis-21420160412-74199-l8k42e/QGIS-final-2_14_1/build/src/plugins/geometry_checker/ui/moc_qgsgeometrycheckerdialog.cxx_parameters
Undefined symbols for architecture x86_64:
  "GDALRasterBand::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, int, int)", referenced from:
      Heatmap::run() in heatmap.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [PlugIns/qgis/libheatmapplugin.so] Error 1
make[1]: *** [src/plugins/heatmap/CMakeFiles/heatmapplugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 77%] Generating ui/moc_qgsgeometrycheckersetuptab.cxx

Problem with gdal it seems... Can you try building like so:

brew -v install qgis-214 --with-gdal-1 --with-r --with-saga-gis --with-orfeo --without-server.

I will build later against gdal2, and see if that makes a difference...

**Comment by ivanmobigis** [comment]
unfortunately i don't have the original console anymore from when I installed qgis-214, but i remember that several deps were upgraded/installed when passing from 2.8 to 2.14, for example qscintilla2 which is incompatible with the qgis-28 version.

**Comment by ivanmobigis** [comment]
ok i will try the gdal-1 build,

thanks a lot for your help.

**Comment by pjduplooy** [comment]
NP
Hope you come right.... I was really hoping to build against gdal2....

**Comment by pjduplooy** [comment]
Was your qt pored from bottle?

**Comment by ivanmobigis** [comment]
the build died coz orfeo didn't compile:

CMake Error at /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeExportBuildSettings.cmake:17 (message):
  The functionality of this module has been dropped as of CMake 2.8.  It was
  deemed harmful (confusing users by changing their compiler).  Please remove
  calls to the CMAKE_EXPORT_BUILD_SETTINGS macro and stop including this
  module.  If this project generates any files for use by external projects,
  remove any use of the CMakeImportBuildSettings module from them.
Call Stack (most recent call first):
  CMakeLists.txt:362 (include)



-- Configuring incomplete, errors occurred!
See also "/tmp/orfeo-4220160413-37754-1vgl0vr/OTB-4.2.1/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/orfeo-4220160413-37754-1vgl0vr/OTB-4.2.1/build/CMakeFiles/CMakeError.log".

..................


Error: osgeo/osgeo4mac/orfeo-42 4.2.1 did not build
Logs:
     /Users/ivan/Library/Logs/Homebrew/orfeo-42/01.cmake
     /Users/ivan/Library/Logs/Homebrew/orfeo-42/01.cmake.cc



i will try without orfeo, so:
brew -v install qgis-214 --with-gdal-1 --with-r --with-saga-gis  --without-server

**Comment by ivanmobigis** [comment]
regarding qt, i believe so:

darwin ivan ~ $ brew info qt
qt: stable 4.8.7 (bottled), HEAD
Cross-platform application and UI framework
https://www.qt.io/
/usr/local/Cellar/qt/4.8.7 (2,816 files, 113.3M)
  Poured from bottle
/usr/local/Cellar/qt/4.8.7_2 (2,815 files, 113.0M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/qt.rb
==> Dependencies
Required: openssl ✔
Optional: d-bus ✘, mysql ✘, postgresql ✔

**Comment by ivanmobigis** [comment]
hello again

it worked !

qgis 2.14 was built and starts up now..i had to uninstall and reinstall pyspatialite to make it happy (libgeos not found, even though it was present) but it works now. i haven't actually tested gdal or grass bindings however.

i'll run it again with gdal-2 just to see what happens.. so:
brew -v install qgis-214  --with-r --with-saga-gis  --without-server

thanks for your help !

-i

**Comment by pjduplooy** [comment]
Hi

Sorry forgot to say, orfeo does not build with current cmake, you have to use a 2.8 cmake for orfeo to build.  I did a brew uninstall cmake, then grabbed a cmake 2.8 rb from homebrews github, installed that, and built orfeo.. Unistalled cmake, and reinstalled the new one.

Bit of an effort, but hey, at least we mac users can have some nice geospatial tools.

**Comment by pjduplooy** [comment]
Glad it worked!!!

Issues that I encountered was that grass 7 refused to start, but it is available in qgis processing.  I also have bit of prob with r and qgis on El Capitan, still sorting that out

**Comment by pjduplooy** [comment]
To give you an indication..

Built postgresql
Built wine
Built openscenegraph
built gdal dependencies
Built gdal
Built cgal and sfcgal
Built postgis (I have changed the rb so that I have 2.2.2)
Built the postgis extensions like pgrouting)
Built ogr_fdw
Built pointcloud extension with its dependencies
Then built osm2pgrouting, osm2pgsql, pcl and pdal
Qgis deps, and qgis
Built the horaoviewer plugin for qgis.

Long process, but well worth the wait....

**Comment by ivanmobigis** [comment]
well building with gdal-2 (not surprisingly) didn't work.. same error:

Undefined symbols for architecture x86_64:
  "GDALRasterBand::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, int, int)", referenced from:
      Heatmap::run() in heatmap.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [PlugIns/qgis/libheatmapplugin.so] Error 1
make[1]: *** [src/plugins/heatmap/CMakeFiles/heatmapplugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

(now i know what to search for!)


so i'm gonna reinstall with gdal 1 and then verify all the components are ok.

-i

**Comment by ivanmobigis** [comment]
just for anyone else who uses this thread.. after re-installing qgis-214 the grass plugin didn't work.

it was looking for:
/usr/local/opt/grass-64/grass-6.4.4/lib/libgrass_I.6.4.4.dylib
when i had:
/usr/local/opt/grass-64/grass-6.4.5/lib/libgrass_I.6.4.5.dylib

i needed to uninstall/reinstall grass-64, then uninstall/reinstall qgis-214.

now it's all working, gdal, grass, postgis and qgis.

thanks heaps to pjduplooy for your help !

-i

**Comment by pjduplooy** [comment]
Glad it worked!!

**Comment by dakcarto** [comment]
Hi,

Thanks for reporting. The `GDALRasterBand::RasterIO` issue in `heatmap.cpp` appears to be present on 10.10 as well. This can be remedied by adding the workaround of disabling the Heatmap plugin for that OS:

https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/qgis-214.rb#L226-L234

Will commit that now.

Please note: this is not an issue with GDAL v2, but an issue with the linking routine in CMake that allows accidental linking to GDAL v1, even though v2 is clearly defined as preferred. So, when the API for v2 is pulled in by the appropriate headers in `include`, but then the v1 libgdal.dylib is linked instead... instant missing symbol.

You can verify this by doing `brew unlink gdal` then building `qgis-214` (with gdal-20 by default) and there should be no issues with GDAL linking. Still looking into how to correctly fix this.

**Comment by ivanmobigis** [comment]
Hi dakcarto,

ok, maybe that's why pjduplooy didn't have the problem, coz he had a different version of cmake installed, for a different reason (2.8, i have 3.5.1).

just for info i tried unlinking gdal1 before the qgis 2-14 install but it won't let me..

```
darwin ivan ~ $ brew unlink gdal
Unlinking /usr/local/Cellar/gdal/1.11.3_1... 230 symlinks removed
darwin ivan ~ $ brew uninstall qgis-214
Uninstalling /usr/local/Cellar/qgis-214/2.14.1... (8,461 files, 195.2M)
darwin ivan ~ $ brew -v install qgis-214 --with-r --with-saga-gis --without-server
==> Installing qgis-214 from osgeo/osgeo4mac
Error: You must `brew link gdal` before osgeo/osgeo4mac/qgis-214 can be installed
darwin ivan ~ $ brew link gdal
Linking /usr/local/Cellar/gdal/1.11.3_1... 171 symlinks created
darwin ivan ~ $ brew -v install qgis-214 --with-gdal-1 --with-r --with-saga-gis  --without-server
==> Installing qgis-214 from osgeo/osgeo4mac
.......


launching with --ignore-dependancies bombs immediately with:

Failed to execute: cmake

-i

**Comment by pjduplooy** [comment]
Hi, I only uses 3.8 for theo orfeo brew.  Reverted to 3.5.1 for qgis

**Comment by dakcarto** [comment]
Couple of notes:

@ivanmobigis wrote:
> ok, maybe that's why pjduplooy didn't have the problem, coz he had a different version of cmake installed, for a different reason (2.8, i have 3.5.1).

When I mentioned CMake I am referring to the setup _inside_ of QGIS's source tree, not necessarily the version.

> just for info i tried unlinking gdal1 before the qgis 2-14 install but it won't let me..
> ...
>  `$ brew -v install qgis-214 --with-r --with-saga-gis --without-server`

When you chose `--with-saga-gis` it added the dependency for `gdal` v1 again. 😉 Doing a simple `brew -dv install qgis-214` should succeed with `gdal` v1 unlinked.

I am looking into a fix for this issue and whether I can get `gdal-20` working for `saga-gis` and updating the orfeo formula to work with `gdal-20` as well.

**Comment by dakcarto** [comment]
Ok, everything should be fixed with latest commits. Builds fine on 10.11.4 now, with `gdal` v1 installed and linked.

**Comment by ecerrillo** [comment]
Hi,

Everything seems to work now, congrats. But there is still a problem. GDAL 2 bindings for Python are not longer working within Python. As suggested by the installation script I already did:

`/usr/local/opt/gdal-20/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/gdal-20.pth`

However, when I try to import as raster:

`dem = gdal.Open('raster.asc')`

It seems that the format is not recognised.

**Comment by dakcarto** [comment]
@ecerrillo, thanks for reporting. Please make a separate issue ticket for the Python-related bug.
