### ISSUE TITLE
Cannot upgrade gdal2 on OS X 10.12.6

### ISSUE THREAD

**Issue by silyko** [OSGeo/homebrew-osgeo4mac#252]
Back to work after a lovely summer holiday. Various updates installed via AppStore (e.g. update to OS X 10.12.6). Now qgis2 is not able to start anymore (crash dump not attached). Tried to upgrade outdated formulae, e.g. gdal2 (was 2.1.3_3, most recent gdal 2.2.0), which fails with:

```bash
(venv_p2) Simons-MacBook-Pro:pc simonkokkendorff$ brew upgrade gdal2
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

==> Upgrading 1 outdated package, with result:
osgeo/osgeo4mac/gdal2 2.2.0
==> Upgrading osgeo/osgeo4mac/gdal2 --with-postgresql
==> Using the sandbox
==> Downloading http://download.osgeo.org/gdal/2.2.0/gdal-2.2.0.tar.gz
Already downloaded: /Users/simonkokkendorff/Library/Caches/Homebrew/gdal2-2.2.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/gdal2/2.2.0 --mandir=/usr/local/Cellar/gdal2/2.2.0/share/man --with-local=/usr/local/Cellar/gdal2/2.2.0 --with-threads --with-libtool --with-pcraster=internal --with-pcids
==> make
==> make install
Error: Operation not permitted - /usr/local/lib/gdalplugins
```

Have ownership of /usr/local, and haven't seen this error before... Any tips?

All the best,
Simon Kokkendorff

**Comment by petrasovaa** [comment]
Have the same problem...

**Comment by spolloni** [comment]
This is related to the new homebrew release, see here: 
https://github.com/Homebrew/homebrew-core/issues/16443

**Comment by petrasovaa** [comment]
I looked at this, but I couldn't quite understand it. Is there a way around it, at least temporary?

**Comment by spolloni** [comment]
The workaround proposed [here](https://github.com/Homebrew/homebrew-core/issues/4892) should work. My sense is that the folks at Homebrew are (understandably) not too keen on making this an established solution and trying to incentivize non-homebrew taps to play by the new rules for security reasons.

**Comment by silyko** [comment]
Thanks for the pointers - will try the workaround.

**Comment by dakcarto** [comment]
Hi @silyko, thanks for reporting! Also, thanks to everyone who contributed.

Should be fixed in 524a5f7. Please try again.

**Comment by silyko** [comment]
Thanks, gdal2 seems to work for me now (without manually creating /usr/local/lib/gdalplugins/<version>)
 However, qgis2 still fails (in upgrading PyQt4) with
```bash
Error: Permission denied - /opt/pyqt-qt4
```
Seems to be missing /usr/local ? Should be reported in a separete issue, I guess...

**Comment by dakcarto** [comment]
@silyko wrote:
> However, qgis2 still fails (in upgrading PyQt4) with
> `Error: Permission denied - /opt/pyqt-qt4`

The `qgis*` formulae have not yet been updated to work with those dependencies (or sandboxing). Working on that today. They will be broken until fixes are applied.

However, that error is a bit baffling, as nothing writes to `/opt/pyqt-qt4`. After I update the `qgis2` formula, please retry, then file a new issue, if it persists. Thanks!

**Comment by pat-s** [comment]
`Error: Permission denied - /opt/pyqt-qt4`

faced the same problem. 
Fixed it with `sudo chmod g+w /usr/local` and then `brew link --overwrite pyqt-qt4`

**Comment by silyko** [comment]
Thx, that worked for me too.

**Comment by dakcarto** [comment]
@silyko you should also run `brew doctor` and fix anything out of sorts, [as noted in this comment](https://github.com/OSGeo/homebrew-osgeo4mac/issues/258#issuecomment-322248802).

Closing issue; reopen if necessary.
