### ISSUE TITLE
does QGIS3 --with-r have to be with "official" homebrew r? 

### ISSUE THREAD

**Issue by luispuerto** [OSGeo/homebrew-osgeo4mac#583]
I was trying to reinstall QGIS3 and before I was using `--with-r` with an r from another tap instead of the official one. Now it seems that it's not longer possible: 

```shell 
==> Reinstalling osgeo/osgeo4mac/qgis3 --with-grass --with-r --with-saga-gis-lts --with-orfeo6
==> Installing dependencies for osgeo/osgeo4mac/qgis3: r
Error: r is already installed from sethrfore/r-srf!
Please `brew uninstall r` first."
```

why??????

I'm using the `sethrfore/r-srf/r` because it's the only r that you can install with homebrew and get all the capabilities. The homebrew regular r doesn't have options anymore and doesn't provide all the capabilities (in the same way the official R installer provides).

**Comment by luispuerto** [comment]
Comparison of the two Rs: 

```shell
brew info r                                                            
r: stable 3.5.2 (bottled)
Software environment for statistical computing
https://www.r-project.org/
/usr/local/Cellar/r/3.5.2 (2,123 files, 56.1MB) *
  Built from source on 2019-01-05 at 12:40:08 with: --with-openblas --with-java --with-libtiff --with-cairo
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/r.rb
==> Dependencies
Build: pkg-config ✔
Required: gcc ✔, gettext ✔, jpeg ✔, libpng ✔, openblas ✔, pcre ✔, readline ✔, xz ✔
==> Analytics
install: 13,589 (30 days), 23,740 (90 days), 109,130 (365 days)
install_on_request: 11,788 (30 days), 21,360 (90 days), 91,562 (365 days)
build_error: 0 (30 days)

$ brew info sethrfore/r-srf/r                                                        
sethrfore/r-srf/r: stable 3.5.2
Software environment for statistical computing
https://www.r-project.org/
/usr/local/Cellar/r/3.5.2 (2,123 files, 56.1MB) *
  Built from source on 2019-01-05 at 12:40:08 with: --with-openblas --with-java --with-libtiff --with-cairo
From: https://github.com/sethrfore/homebrew-r-srf/blob/master/r.rb
==> Dependencies
Build: pkg-config ✔
Required: gcc ✔, gettext ✔, jpeg ✔, libpng ✔, pcre ✔, readline ✔, xz ✔
Optional: openblas ✔, texinfo ✔, libtiff ✔, cairo ✔, icu4c ✔, pango ✔
==> Requirements
Required: x11 ✔
Optional: java ✔
==> Options
--with-cairo
	Build with cairo support
--with-icu4c
	Build with icu4c support
--with-java
	Build with java support
--with-libtiff
	Build with libtiff support
--with-openblas
	Build with openblas support
--with-pango
	Build with pango support
--with-texinfo
	Build with texinfo support
==> Analytics
install: 13,589 (30 days), 23,740 (90 days), 109,130 (365 days)
install_on_request: 11,788 (30 days), 21,360 (90 days), 91,562 (365 days)
build_error: 0 (30 days)
```

**Comment by luispuerto** [comment]
PS/ I have the same problem as in #520 or at least it's suggesting that.

**Comment by luispuerto** [comment]
```shell 
==> Installing osgeo/osgeo4mac/qgis3 --with-grass --with-saga-gis-lts --with-orfeo6
==> Cloning https://github.com/qgis/QGIS.git
Updating /Users/lpuerto/Library/Caches/Homebrew/qgis3--git
==> Checking out branch release-3_4
Already on 'release-3_4'
Your branch is up to date with 'origin/release-3_4'.
HEAD is now at 5364afe4 [themes] Last round of theme fix (hopefully)
==> Patching
patching file cmake/FindQsci.cmake

In case you have installed another version of Python (Anaconda, Miniconda or if you used the installer provided by python.org).

If the installation failed due to the problem reported in https://github.com/OSGeo/homebrew-osgeo4mac/issues/520

Try after doing:

    $ brew unlink python && brew link --force python

The installation will continue, but remember the above.
30.29.28.27.26.25.24.23.22.21.20.19.18.17.16.15.14.13.12.11.10.09.08.07.06.05.04.03.02.01.00.
==> Cloning https://gitlab.orfeo-toolbox.org/orfeotoolbox/qgis-otb-plugin.git
Updating /Users/lpuerto/Library/Caches/Homebrew/qgis3--otb--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at a1762b7 respect naming conventions for qgis providers
==> Downloading https://gist.githubusercontent.com/fjperini/009a5dda278c1a10e0758865d149820c/raw/ff5a239ac525d8e760d6f02
Already downloaded: /Users/lpuerto/Library/Caches/Homebrew/downloads/c76aac94b4eac16a2e775205362eafdc47404aaebad529a64279f5eb2917d7d1--OTBAlgorithmProvider.patch
==> Downloading https://gist.githubusercontent.com/fjperini/53f53daf78ab5e203fd81322ea5c3a2f/raw/783b17df86d8e88c41e26a3
Already downloaded: /Users/lpuerto/Library/Caches/Homebrew/downloads/92632cfec6bff357d3923d6ae56eb0af56ac7f8d85ba52babc61c6389b068a95--OTBUtils.patch
==> patch -p1 -i /private/tmp/qgis3-20190113-59504-1fqu0c/OTBAlgorithmProvider.patch
Last 15 lines from /Users/lpuerto/Library/Logs/Homebrew/qgis3/01.patch:
2019-01-13 16:14:49 +0200

patch
-p1
-i
/private/tmp/qgis3-20190113-59504-1fqu0c/OTBAlgorithmProvider.patch

patching file python/plugins/otb/OTBAlgorithmProvider.py
Hunk #1 FAILED at 53.
Hunk #2 FAILED at 172.
Hunk #3 FAILED at 209.
patch unexpectedly ends in middle of line
Hunk #4 succeeded at 134 with fuzz 2 (offset -106 lines).
3 out of 4 hunks FAILED -- saving rejects to file python/plugins/otb/OTBAlgorithmProvider.py.rej

If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
osgeo/osgeo4mac

These open issues may also help:
Problem when running brew upgrade qGis3 https://github.com/OSGeo/homebrew-osgeo4mac/issues/581
brew install osgeo/osgeo4mac/qgis3 fails ... usr/local/Cellar/qgis3 folder is missing https://github.com/OSGeo/homebrew-osgeo4mac/issues/553
QGIS3 crashes when I click on QGIS → About QGIS  https://github.com/OSGeo/homebrew-osgeo4mac/issues/582
qgis3 formula needs unlinked grass7 https://github.com/OSGeo/homebrew-osgeo4mac/issues/508
does QGIS3 --with-r have to be with "official" homebrew r?  https://github.com/OSGeo/homebrew-osgeo4mac/issues/583
brew install osgeo/osgeo4mac/qgis3 fails on macOSX HighSierra https://github.com/OSGeo/homebrew-osgeo4mac/issues/520
QGIS3 save fails and corrupts app https://github.com/OSGeo/homebrew-osgeo4mac/issues/455
```

**Comment by fjperini** [comment]
Yesterday I reinstalled everything and I did not have that problem.
But I was thinking about not using default `homebrew/core/r`. We could use `sethrfore/r-srf/r` by default, what do you say @luispuerto? 
We would only have to solve the situation of the `cairo` dependency.

**Comment by luispuerto** [comment]
Perhaps we have an option? Something like `--with-r-complete` or similar? Yeah we need cairo to build a complete R. The main issue here seems to be that the QGIS3 formula doesn’t seem the like the `sethrfore/r-surf/r`. I understand that if you don’t have r it will go ahead and install it, but you already have it, why should be so picky?

**Comment by fjperini** [comment]
I think the inconevniente is because two versions of `r` will be installed in the same path. `homebrew/core/r` was updated and since then it may not be consistent with the one of sethrfore.

If we upload r to this repository?

**Comment by nickrobison** [comment]
I think a better solution would be to check if R is already installed on the system, and if not, install R from homebrew core.

I would definitely not be in support of maintaining our own R package.

**Comment by luispuerto** [comment]
I've seen that R from Core has been update since the last R update a couple of times, I really don't now why, but perhaps to remove the options. Before it was possible to build R from Core `--with-open-blas` and that option isn't there anymore. In fact, now it's _optionless_, but it's something they already announced more than a half a year ago. They wanted all the formulas to drop the options. The main reason, it's easier to maintain. 

If I can't install something with homebrew with the same capabilities —or more— as the binary provided by the developer... why am I going to install it with homebrew?

**Comment by luispuerto** [comment]
@nickrobison I totally agree with you in both things. R is a statistical software/language/library. I can be used in GIS in combination with QIGS or even alone, of course, but definitely shouldn't be maintained here.

**Comment by fjperini** [comment]
@luispuerto @nickrobison Ok, I will add this to the formula of `qgis3`:

```
if build.with?("r") || brewed_r?
    depends_on "sethrfore/r-srf/r"
end
```

**Comment by fjperini** [comment]
I already solved this with:

```
if build.with?("r")
  unless Formula["r"].opt_prefix.exist?
    depends_on "r"
  end
end
```
Then for everything else with this is enough:

```
if build.with?("r") || brewed_r?
```

With only install `r` if it is not installed, and will continue with the installation of `qgis3` in case it is already installed.

I already apply the changes!

**Comment by luispuerto** [comment]
this is fixed 👍

**Comment by fjperini** [comment]
@luispuerto Great!
I'm looking at the `No module named 'otb.OtbAlgorithmProvider'`, when `qgis3` applies the patch, the error is still present. If I apply the changes manually everything works correctly.

Can you help me with this? There may be an error in the format of the file given that they are equal in content :sweat_smile:

After compiling `qgis3` ([formula](https://gist.githubusercontent.com/fjperini/bfe8bb673229aefd2cabfbdb890474d2/raw/19ce234b4c00fc71b76b417f773794122716e171/qgis3.rb)), if the error is present, check the difference of these [otb.zip](https://github.com/OSGeo/homebrew-osgeo4mac/files/2754061/otb.zip) files with those of `QGIS.app/Contents/Resources/python/plugins/otb`.

You can change them by these to verify that it works.

If the problem with the patch persists, a solution is to temporarily replace those files.

**Comment by luispuerto** [comment]
I think I'm going to open a issue with this... have more sense.

**Comment by fjperini** [comment]
@luispuerto It tries to erase the files of HOMEBREW CACHE, it seems that it uses a previous version of the patch.
